version: '3'

services:
  PHPMailer-test:
    image: phpmailer-test:latest
    build: ./
    container_name: PHPMailer-test
    tty: true
    volumes:
      - ./:/mnt/:cached
  sendgrid-maildev:
    image: ykanazawa/sendgrid-maildev
    hostname: sendgrid-maildev
    environment:
      - SENDGRID_DEV_API_KEY=SG.xxxxx
    container_name: sendgrid-maildev
    ports:
      - 1080:1080

